import 'package:flutter/material.dart';

class Listed extends StatelessWidget {
  Listed({super.key});

  final List<String> rzeczyKtoreKocham = [
    "Twój piękny uśmiech",
    "Twoje dzień dobry",
    "Twoje dobranoc",
    "Twoje oczy",
    "Twoje usta",
    "Twoje poczucie humoru",
    "To że moge być przy tobie sobą",
    "To że starasz się",
    "To że moge zawsze na ciebie liczyć",
    "To że zawsze wiesz co powiedzieć mi",
    "To że bierzesz na powaznie moje zdanie",
    "Twoje gesty",
    "Twoj tok myślenia",
    "Za to że potrafisz mnie zawsze czymś zaskoczyć",
    "Za to że potrafisz powiedzieć nie",
    "Za to że dalej walczysz",
    "Za twoje niedoskonałości",
    "Za wspólny język",
    "Za wyrozumienie",
    "Za pomysłowość",
    "Za otwartość",
    "Za nasz wspólny czas",
    "Za to że zawsze oglądasz jak gram w phasmophobie",
    "Za to że mogę się rozwijać",
    "Za to że dajemy sobie przestrzeń na swoje zainteresowania",
    "Za twój urok",
    "Za twoją chęć dobra",
    "Za towarzystwo",
    "Za ciągły niedosyt",
    "Za twoją motywacje o 3 w nocy",
    "Za twoją wizje związku",
    "Za to że nasz związek skończy się małżeństwem",
    "Za twoją samokontrole",
    "Za twój styl bycia",
    "Za to że się zmieniłaś, i dalej się zmieniasz",
    "Za twoje umiejętności manualne",
    "Za reelsy pfff",
    "Za codzienne pisanie",
    "Za twoje wybory",
    "Za to że jesteś lepsza",
    "Za twój temperament",
    "Za złe jak i dobre decyzje",
    "Za to że mi ufasz",
    "Za to że mam na ciebie wpływ",
    "Za to że nie uważasz za kontrolowanie troskę",
    "Za to że wolisz zostać w domu niż imprezować", 
    "Za to że nie masz swoich używek",
    "Za to jak wypowiadasz sie o mnie",
    "Za to że uważasz mnie za kogoś idealnego",
    "Za to że bardzo mocno wpływasz na mnie",
    "Za to że potrafisz zmienić moje zachowanie",
    "Za to że się martwisz",
    "Za twoją troske",
    "Za twoja prawdomówność",
    "Za nasze żarty",
    "Za naszą solidarność",
    "Za to że się nie wstydzimy",
    "Za to że nigdy się nie poddałaś",
    "Za twoje preferencje",
    "Za twoją akceptacje",
    "Za zmysły",
    "Za naszą intymną sfere",
    "Twoje dłonie",
    "Twoją szyje",
    "To za co uważasz całuski w czółko i w rączki uwu",
    "Za twoją asertywność",
    "Za twój rozsądek",
    "Za twoją dojrzałość mentalną",
    "Za to że jesteś",
    "Za twoje stanowcze nie jeżeli chodzi o znajomych płci przeciwnej(mówiąc inaczej zdrowy rozsądek i troske)",
    "Za to że chcesz rozwijac się",
    "Za twój trud",
    "Za twoje łzy",
    "Za to że potrafisz komuś w twarz powiedzieć żeby sie ogarnął",
    "Za czytanie",
    "Za oglądanie seriali/filmów",
    "Za wizje zestarzenia się razem",
    "Za niezachłanność",
    "Za twoją emocjonalność",
    "Za twój ambiwertyzm",
    "Za to że widzisz czasami szklanke do połowy pełną",
    "Za to że widzisz czasami szklanke do połowy pustą",
    "Za twoje cechy charakteru które cię uzupełniają",
    "Za twoją seksowność :3",
    "ZA LOJALNOŚĆ!!!!!!!",
    "Za obowiązkowość",
    "Za to że mimo wszystko jesteś pracowita",
    "Za samodzielność",
    "Za niesamodzielność",
    "Za szczerość",
    "Za uczciwość",
    "Za brak stawiania mnie w obłudzie",
    "Za to że starasz sie przy mnie zachować spokój(czasami sie nie da)",
    "Kocham cie za nasze rozmowy do późnej nocy",
    "Kocham cie za twoją ugodowość",
    "Za twoj perfekcyjny wygląd",
    "Za twoją sumienność",
    "Za twoje spóźnialstwo",
    "Za twoje 'już zchodze'",
    "Za twoją piękną figure",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Rzeczy, które kocham w Tobie",
          style: TextStyle(fontSize: 20),
        ),
        centerTitle: true,
        backgroundColor: const Color.fromRGBO(199, 199, 199, 1),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0), // Dodaj marginesy
        child: ListView.builder(
          itemCount: rzeczyKtoreKocham.length,
          itemBuilder: (context, index) {
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "${index + 1}. ${rzeczyKtoreKocham[index]}", // Numeracja
                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const Divider(thickness: 1, height: 20),
              ],
            );
          },
        ),
      ),
    );
  }
}
